Invalid parameter to check result. Fixes #180, fixes #181
Error: Return value must be of type string, null returned.

The result get_details() method expects a string. So this has
been changed to an empty string ''.